spring:
  config:
    activate:
      on-profile: local
    import: application-secret.properties
  datasource:
    url: jdbc:h2:tcp://localhost/~/test;DATABASE_TO_UPPER=false;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql:
        dialect: org.hibernate.dialect.H2Dialect

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

jwt:
  header: Authorization
  secret: ${JWT_SECRET}
  access-token:
    expire-length: ${ACCESS_TOKEN_EXPIRED_TIME} # 10분
  refresh-token:
    expire-length: ${REFRESH_TOKEN_EXPIRED_TIME}  # 2시간

aws-property:
  aws-region: ${AWS_REGION}
  s3-bucket-name: ${AWS_BUCKET_NAME}
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}