name: Katchup Server CI & CD

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'
          cache: gradle

      - name: set environment variables
        working-directory: ./
        run: |
          pwd
          touch src/main/resources/application-secret.properties
          echo ${{ secrets.ENV }} >> src/main/resources/application-secret.properties

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build
        shell: bash

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_NAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest

      - name: Pull and Deploy
        uses: appleboy/ssh-action@master

        # if:  github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'develop'
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_REMOTE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "Pull and Deploy"
            sudo docker stop $(sudo docker ps -q)
            sudo docker rm -f $(docker ps -qa)
            docker pull ${{ secrets.DOCKER_NAME }}/${{ secrets.DOCKER_REPOSITORY }}
            docker run -d -p 8080:8080 --name katchup-dev ${{ secrets.DOCKER_NAME }}/${{ secrets.DOCKER_REPOSITORY }}
            docker image  rm -f $(docker images -f "dangling=true" -q)
